version: "3.9"
services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $DATABASE_DSN"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  migrate:
    image: migrate/migrate
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - "../migrations:/migrations"
    command: ["-path", "/migrations/", "-database", "$DATABASE_DSN", "up"]
  web:
    build:
      context: ../
      args:
        GO_VERSION: $GO_VERSION
    env_file:
      - "local.env"
    environment:
      SERVICE_DATABASE_DSN: $DATABASE_DSN
    depends_on:
      database:
        condition: service_healthy
      migrate:
        condition: service_started
    ports:
      - "5000:5000"